import dog from '../assets/img/dog.jpg';
import cat from '../assets/img/cat.jpg';
import bird from '../assets/img/bird.png';
import elephant from '../assets/img/elephant.jpg';
import fish from '../assets/img/fish.jpg';
import tiger from '../assets/img/tiger.jpg';
import lion from '../assets/img/lion.jpg';
import snake from '../assets/img/snake.jpg';
import whale from '../assets/img/whale.jpg';
import hamster from '../assets/img/hamster.jpg';
import animalsBg from '../assets/img/animals-bg.jpg';
import numbersBg from '../assets/img/numbers-bg.png';
import grammarBg from '../assets/img/grammar-bg.jpg';

const animals = {
  type: 'animals',
  img: animalsBg,
  tests: [
    [
      {
        _id: 0,
        ques: 'How am I called?',
        answer: 'dog',
        doneBy: [],
        img: dog,
      },
      {
        _id: 1,
        ques: 'How am I called?',
        answer: 'tiger',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 2,
        ques: 'How am I called?',
        answer: 'lion',
        doneBy: [],
        img: lion,
      },
      {
        _id: 3,
        ques: 'How am I called?',
        answer: 'fish',
        doneBy: [],
        img: fish,
      },
      {
        _id: 4,
        ques: 'How am I called?',
        answer: 'cat',
        doneBy: [],
        img: cat,
      },
    ],
    [
      {
        _id: 5,
        ques: 'How am I called?',
        answer: 'bird',
        doneBy: [],
        img: bird,
      },
      {
        _id: 6,
        ques: 'How am I called?',
        answer: 'snake',
        doneBy: [],
        img: snake,
      },
      {
        _id: 7,
        ques: 'How am I called?',
        answer: 'elephant',
        doneBy: [],
        img: elephant,
      },
      {
        _id: 8,
        ques: 'How am I called?',
        answer: 'whale',
        doneBy: [],
        img: whale,
      },
      {
        _id: 9,
        ques: 'How am I called?',
        answer: 'hamster',
        doneBy: [],
        img: hamster,
      },
    ],
  ],
};
const practice = {
  type: 'practice',
  tests: [
    [
      {
        _id: 0,
        ques: 'How am I called?',
        answer: 'hospital',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/ptx8sl4hvx0yphw66agj.png',
      },
      {
        _id: 1,
        ques: 'How am I called?',
        answer: 'museum',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729862/English/objects/k5buj4ujvc2iwn3badht.png',
      },
      {
        _id: 2,
        ques: 'How am I called?',
        answer: 'theater',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/uyu0hbgv0snw1rj0iwx1.png',
      },
      {
        _id: 3,
        ques: 'How am I called?',
        answer: 'market',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729861/English/objects/yhwvqt5o6d9mpbfxi05p.png',
      },
      {
        _id: 4,
        ques: 'How am I called?',
        answer: 'town',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729870/English/objects/n7quumfggvdnrpl181wr.png',
      },
    ],
    [
      {
        _id: 5,
        ques: 'How am I called?',
        answer: 'restaurant',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/tni0i9dtedcfhfiws2hf.png',
      },
      {
        _id: 6,
        ques: 'How am I called?',
        answer: 'hotel',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/eli14fpvzjfsbmwktzeg.png',
      },
      {
        _id: 7,
        ques: 'How am I called?',
        answer: 'fire station',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/vj2jwkycvnjqrq1w8pbq.png',
      },
      {
        _id: 8,
        ques: 'How am I called?',
        answer: 'police station',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729864/English/objects/jhy4utmzpkoxggxjht5y.png',
      },
      {
        _id: 9,
        ques: 'How am I called?',
        answer: 'bus station',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729853/English/objects/ow878bii5nlk0o5dbfqx.png',
      },
    ],
    [
      {
        _id: 10,
        ques: 'How am I called?',
        answer: 'shop',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729862/English/objects/aboi1upztbfgfwtayatj.png',
      },
      {
        _id: 11,
        ques: 'How am I called?',
        answer: 'home',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/jljaouxiutz47fqo0hj5.png',
      },
      {
        _id: 12,
        ques: 'How am I called?',
        answer: 'electricity',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729859/English/objects/yed6zdoovyfwqdu8qzx4.png',
      },
      {
        _id: 13,
        ques: 'How am I called?',
        answer: 'apartment',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729852/English/objects/rqnnhboylldz5q9wgadh.png',
      },
      {
        _id: 14,
        ques: 'How am I called?',
        answer: 'sofa',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/z26qw25bl7oayvfczx1b.png',
      },
    ],
    [
      {
        _id: 15,
        ques: 'How am I called?',
        answer: 'water',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/ybohpyljeqwrtnnj5bi4.png',
      },
      {
        _id: 16,
        ques: 'How am I called?',
        answer: 'kitchen',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729864/English/objects/fmoupdliv94daydnhfrs.png',
      },
      {
        _id: 17,
        ques: 'How am I called?',
        answer: 'watch',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/ex179qdpamvdhnvkgptb.png',
      },
      {
        _id: 18,
        ques: 'How am I called?',
        answer: 'dining room',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/lwckmuox4qyb1ndvcogx.png',
      },
      {
        _id: 19,
        ques: 'How am I called?',
        answer: 'bedroom',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729853/English/objects/covo2jvjhrgefpytenb0.png',
      },
    ],
    [
      {
        _id: 20,
        ques: 'How am I called?',
        answer: 'living room',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729859/English/objects/ccqzxps9xyclaeejlurs.png',
      },
      {
        _id: 21,
        ques: 'How am I called?',
        answer: 'bathroom',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/zi3yw0nkll6tw0vgagmn.png',
      },
      {
        _id: 22,
        ques: 'How am I called?',
        answer: 'toilet',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/hzmmussobcl45npipmjf.png',
      },
      {
        _id: 23,
        ques: 'How am I called?',
        answer: 'garden',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729856/English/objects/mikktgbgpyehrsoihzdb.png',
      },
      {
        _id: 24,
        ques: 'How am I called?',
        answer: 'gas',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/i6oedykjtienesp2ithk.png',
      },
    ],
    [
      {
        _id: 25,
        ques: 'How am I called?',
        answer: 'computer',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/jqspxzezratlaqgx1d2q.png',
      },
      {
        _id: 26,
        ques: 'How am I called?',
        answer: 'lamp',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729860/English/objects/ldqnrcodpjscvm6xyemh.png',
      },
      {
        _id: 27,
        ques: 'How am I called?',
        answer: 'rug',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729863/English/objects/glzklv5n8pqobryjlptj.png',
      },
      {
        _id: 28,
        ques: 'How am I called?',
        answer: 'drink',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/dtpwvdzjgt4qw23khbpy.png',
      },
      {
        _id: 29,
        ques: 'How am I called?',
        answer: 'sleep',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729864/English/objects/auvbnbphbk7xihmnuxcj.png',
      },
    ],
    [
      {
        _id: 30,
        ques: 'How am I called?',
        answer: 'walk',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/n0indsur4inswu6lwmbx.png',
      },
      {
        _id: 31,
        ques: 'How am I called?',
        answer: 'cook',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729854/English/objects/j9vod3vwtqr7u9nuhnna.png',
      },
      {
        _id: 32,
        ques: 'How am I called?',
        answer: 'climb',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729853/English/objects/qtg0yzbfcj3fhgg8utiq.png',
      },
      {
        _id: 33,
        ques: 'How am I called?',
        answer: 'swim',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/jevcrpgjgwbrtoce85db.png',
      },
      {
        _id: 34,
        ques: 'How am I called?',
        answer: 'remember',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729862/English/objects/zwjxwlzgtfykwcuibjty.png',
      },
    ],
    [
      {
        _id: 35,
        ques: 'How am I called?',
        answer: 'fly',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729857/English/objects/rrljunrrdnpnjjzlrpjd.png',
      },
      {
        _id: 36,
        ques: 'How am I called?',
        answer: 'know',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729860/English/objects/t8pehve6c0zuqzsngugx.png',
      },
      {
        _id: 37,
        ques: 'How am I called?',
        answer: 'come in',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/igx3se02ffegziu9mwgx.png',
      },
      {
        _id: 38,
        ques: 'How am I called?',
        answer: 'work',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729868/English/objects/mo3ktw3tcwnfrttiozdr.png',
      },
      {
        _id: 39,
        ques: 'How am I called?',
        answer: 'build',
        doneBy: [],
        img: tiger,
      },
    ],
    [
      {
        _id: 40,
        ques: 'How am I called?',
        answer: 'throw',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 41,
        ques: 'How am I called?',
        answer: 'cut',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 42,
        ques: 'How am I called?',
        answer: 'clean',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 43,
        ques: 'How am I called?',
        answer: 'feed',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 44,
        ques: 'How am I called?',
        answer: 'eat',
        doneBy: [],
        img: tiger,
      },
    ],
    [
      {
        _id: 45,
        ques: 'How am I called?',
        answer: 'cucumber',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 46,
        ques: 'How am I called?',
        answer: 'egg',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 47,
        ques: 'How am I called?',
        answer: 'cookie',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 48,
        ques: 'How am I called?',
        answer: 'tea',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 49,
        ques: 'How am I called?',
        answer: 'pie',
        doneBy: [],
        img: tiger,
      },
    ],
    [
      {
        _id: 50,
        ques: 'How am I called?',
        answer: 'hot dog',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 51,
        ques: 'How am I called?',
        answer: 'cereal',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 52,
        ques: 'How am I called?',
        answer: 'onion',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 53,
        ques: 'How am I called?',
        answer: 'coffee',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 54,
        ques: 'How am I called?',
        answer: 'plum',
        doneBy: [],
        img: tiger,
      },
    ],
    [
      {
        _id: 55,
        ques: 'How am I called?',
        answer: 'candy',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 56,
        ques: 'How am I called?',
        answer: 'potato',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 57,
        ques: 'How am I called?',
        answer: 'peach',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 58,
        ques: 'How am I called?',
        answer: 'pepper',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 59,
        ques: 'How am I called?',
        answer: 'cheese',
        doneBy: [],
        img: tiger,
      },
    ],
    [
      {
        _id: 60,
        ques: 'How am I called?',
        answer: 'tomato',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 61,
        ques: 'How am I called?',
        answer: 'apple',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 62,
        ques: 'How am I called?',
        answer: 'lettuce',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 63,
        ques: 'How am I called?',
        answer: 'bread',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 64,
        ques: 'How am I called?',
        answer: 'morning',
        doneBy: [],
        img: tiger,
      },
    ],
    [
      {
        _id: 65,
        ques: 'How am I called?',
        answer: 'afternoon',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 66,
        ques: 'How am I called?',
        answer: 'evening',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 67,
        ques: 'How am I called?',
        answer: 'night',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 68,
        ques: 'How am I called?',
        answer: 'month',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 69,
        ques: 'How am I called?',
        answer: 'week',
        doneBy: [],
        img: tiger,
      },
    ],
    [
      {
        _id: 70,
        ques: 'How am I called?',
        answer: 'year',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 71,
        ques: 'How am I called?',
        answer: 'summer',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 72,
        ques: 'How am I called?',
        answer: 'winter',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 73,
        ques: 'How am I called?',
        answer: 'winter',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 74,
        ques: 'How am I called?',
        answer: 'autumn',
        doneBy: [],
        img: tiger,
      },
    ],
    [
      {
        _id: 75,
        ques: 'How am I called?',
        answer: 'spring',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 76,
        ques: 'How am I called?',
        answer: 'young',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 77,
        ques: 'How am I called?',
        answer: 'old',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 78,
        ques: 'How am I called?',
        answer: 'beautiful',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 79,
        ques: 'How am I called?',
        answer: 'ugly',
        doneBy: [],
        img: tiger,
      },
    ],
    [
      {
        _id: 80,
        ques: 'How am I called?',
        answer: 'poor',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 81,
        ques: 'How am I called?',
        answer: 'rich',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 82,
        ques: 'How am I called?',
        answer: 'warm',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 83,
        ques: 'How am I called?',
        answer: 'cool',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 84,
        ques: 'How am I called?',
        answer: 'clean',
        doneBy: [],
        img: tiger,
      },
    ],
    [
      {
        _id: 85,
        ques: 'How am I called?',
        answer: 'dirty',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 86,
        ques: 'How am I called?',
        answer: 'family',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 87,
        ques: 'How am I called?',
        answer: 'guard',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 88,
        ques: 'How am I called?',
        answer: 'children',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 89,
        ques: 'How am I called?',
        answer: 'king',
        doneBy: [],
        img: tiger,
      },
    ],
    [
      {
        _id: 90,
        ques: 'How am I called?',
        answer: 'nurse',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 91,
        ques: 'How am I called?',
        answer: 'driver',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 92,
        ques: 'How am I called?',
        answer: 'doctor',
        doneBy: [],
        img: tiger,
      },
      {
        _id: 93,
        ques: 'How am I called?',
        answer: 'waiter',
        doneBy: [],
        img: tiger,
      },
    ],
  ],
  img: '',
};
const numbers = {
  type: 'numbers',
  img: numbersBg,

  tests: [
    [
      {
        _id: 0,
        ques: 'How do you say this number?',
        answer: 'one',
        doneBy: ['Adir Buskila'],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/imzu3z5jkuejez1xddur.png',
      },
      {
        _id: 1,
        ques: 'How do you say this number?',
        answer: 'two',
        doneBy: ['Adir Buskila'],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/dfdwp5qxanii1lm0mkwd.png',
      },
      {
        _id: 2,
        ques: 'How do you say this number?',
        answer: 'three',
        doneBy: ['Adir Buskila'],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/ppsjjs6srfhibileuvcb.png',
      },
      {
        _id: 3,
        ques: 'How do you say this number?',
        answer: 'four',
        doneBy: ['Adir Buskila'],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/xoh4gbx3k2msue21jwht.png',
      },
      {
        _id: 4,
        ques: 'How do you say this number?',
        answer: 'five',
        doneBy: ['Adir Buskila'],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/jmxi0espyplpl90abo4h.png',
      },
    ],
    [
      {
        _id: 5,
        ques: 'How do you say this number?',
        answer: 'six',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/cpxqxxicrmz4sgfjh3zy.png',
      },
      {
        _id: 6,
        ques: 'How do you say this number?',
        answer: 'seven',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/zujac7d5vqn0comxfdgk.png',
      },
      {
        _id: 7,
        ques: 'How do you say this number?',
        answer: 'eight',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/l8qzwnkyroiac33jdmzp.png',
      },
      {
        _id: 8,
        ques: 'How do you say this number?',
        answer: 'nine',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/rccosygjuptc0i1bynpa.png',
      },
      {
        _id: 9,
        ques: 'How do you say this number?',
        answer: 'zero',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721282/English/numbers/tqjx8i0vucpzohvzkrin.png',
      },
    ],
    [
      {
        _id: 10,
        ques: 'How do you say this number?',
        answer: 'ten',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/rqsjxvtcsx1baxogqogu.png',
      },
      {
        _id: 11,
        ques: 'How do you say this number?',
        answer: 'eleven',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/ypxqdldkc0uofxyzdi9i.png',
      },
      {
        _id: 12,
        ques: 'How do you say this number?',
        answer: 'twelve',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721282/English/numbers/pmfi080ooslqbvvvwt1q.png',
      },
      {
        _id: 13,
        ques: 'How do you say this number?',
        answer: 'thirteen',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/vorjpwcg3x3hpyohs7d8.png',
      },
      {
        _id: 14,
        ques: 'How do you say this number?',
        answer: 'fourteen',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/vsxaaoc3is9ey4bwolks.png',
      },
    ],
    [
      {
        _id: 15,
        ques: 'How do you say this number?',
        answer: 'fifteen',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/jungjtihndn0eljgrbaz.png',
      },
      {
        _id: 16,
        ques: 'How do you say this number?',
        answer: 'sixteen',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/zibiic9hvizyvr7ddjf2.png',
      },
      {
        _id: 17,
        ques: 'How do you say this number?',
        answer: 'seventeen',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/mfaeudjpwdfmmjrzwvsp.png',
      },
      {
        _id: 18,
        ques: 'How do you say this number?',
        answer: 'eighteen',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/ns4avdolscqhuieghou6.png',
      },
      {
        _id: 19,
        ques: 'How do you say this number?',
        answer: 'nineteen',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/zn1dygpczuawkjoy6hdn.png',
      },
    ],
    [
      {
        _id: 20,
        ques: 'How do you say this number?',
        answer: 'twenty',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721282/English/numbers/e01oydpn6dbp4fltlnt5.png',
      },
      {
        _id: 21,
        ques: 'How do you say this number?',
        answer: 'thirty',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/psxf7vlzl20mlywabd1e.png',
      },
      {
        _id: 22,
        ques: 'How do you say this number?',
        answer: 'forty',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/zeeup3zvmdwxb80vjdhc.png',
      },
      {
        _id: 23,
        ques: 'How do you say this number?',
        answer: 'fifty',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/uoosk54w8srxz8ca2hup.png',
      },
      {
        _id: 24,
        ques: 'How do you say this number?',
        answer: 'sixty',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/mn2uozoz1pnb32yhrtlf.png',
      },
    ],
    [
      {
        _id: 25,
        ques: 'How do you say this number?',
        answer: 'seventy',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/pqo2ouqpivjxhcti57gx.png',
      },
      {
        _id: 26,
        ques: 'How do you say this number?',
        answer: 'eighty',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/nqwsebyvjsoiavk4zqyr.png',
      },
      {
        _id: 27,
        ques: 'How do you say this number?',
        answer: 'ninety',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/pjgder29xvef8ed5dhoi.png',
      },
      {
        _id: 28,
        ques: 'How do you say this number?',
        answer: 'one hundred',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/r42il9slxkhlw7nxevqp.png',
      },
      {
        _id: 29,
        ques: 'How do you say this number?',
        answer: 'one thousand',
        doneBy: [],
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/stwvxh2mbrlsamivhjpf.png',
      },
    ],
  ],
};
const grammar = {
  type: 'grammar',
  img: grammarBg,
  tests: [
    [
      {
        _id: 0,
        ques: 'Eat in past simple',
        answer: 'ate',
        doneBy: [],
      },
      {
        _id: 1,
        ques: 'Sleep in past simple',
        answer: 'slept',
        doneBy: [],
      },
      {
        _id: 2,
        ques: 'Run in past simple',
        answer: 'ran',
        doneBy: [],
      },
      {
        _id: 3,
        ques: 'Throw in past simple',
        answer: 'threw',
        doneBy: [],
      },
      {
        _id: 4,
        ques: 'Throw in past simple',
        answer: 'threw',
        doneBy: [],
      },
    ],
  ],
};

export const categories = [animals, numbers, practice, grammar];

export const checkIfDone = (username, test) => {
  return test.every((t) => t.doneBy.includes(username));
};
