const practice = {
  type: 'practice',
  tests: [
    [
      {
        _id: 'prac-0',
        ques: 'How am I called?',
        answer: 'hospital',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/ptx8sl4hvx0yphw66agj.png',
      },
      {
        _id: 'prac-1',
        ques: 'How am I called?',
        answer: 'museum',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729862/English/objects/k5buj4ujvc2iwn3badht.png',
      },
      {
        _id: 'prac-2',
        ques: 'How am I called?',
        answer: 'theater',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/uyu0hbgv0snw1rj0iwx1.png',
      },
      {
        _id: 'prac-3',
        ques: 'How am I called?',
        answer: 'market',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729861/English/objects/yhwvqt5o6d9mpbfxi05p.png',
      },
      {
        _id: 'prac-4',
        ques: 'How am I called?',
        answer: 'town',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729870/English/objects/n7quumfggvdnrpl181wr.png',
      },
    ],
    [
      {
        _id: 'prac-5',
        ques: 'How am I called?',
        answer: 'restaurant',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/tni0i9dtedcfhfiws2hf.png',
      },
      {
        _id: 'prac-6',
        ques: 'How am I called?',
        answer: 'hotel',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/eli14fpvzjfsbmwktzeg.png',
      },
      {
        _id: 'prac-7',
        ques: 'How am I called?',
        answer: 'fire station',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/vj2jwkycvnjqrq1w8pbq.png',
      },
      {
        _id: 'prac-8',
        ques: 'How am I called?',
        answer: 'police station',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729864/English/objects/jhy4utmzpkoxggxjht5y.png',
      },
      {
        _id: 'prac-9',
        ques: 'How am I called?',
        answer: 'bus station',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729853/English/objects/ow878bii5nlk0o5dbfqx.png',
      },
    ],
    [
      {
        _id: 'prac-10',
        ques: 'How am I called?',
        answer: 'shop',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729862/English/objects/aboi1upztbfgfwtayatj.png',
      },
      {
        _id: 'prac-11',
        ques: 'How am I called?',
        answer: 'home',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/jljaouxiutz47fqo0hj5.png',
      },
      {
        _id: 'prac-12',
        ques: 'How am I called?',
        answer: 'electricity',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729859/English/objects/yed6zdoovyfwqdu8qzx4.png',
      },
      {
        _id: 'prac-13',
        ques: 'How am I called?',
        answer: 'apartment',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729852/English/objects/rqnnhboylldz5q9wgadh.png',
      },
      {
        _id: 'prac-14',
        ques: 'How am I called?',
        answer: 'sofa',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/z26qw25bl7oayvfczx1b.png',
      },
    ],
    [
      {
        _id: 'prac-15',
        ques: 'How am I called?',
        answer: 'water',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/ybohpyljeqwrtnnj5bi4.png',
      },
      {
        _id: 'prac-16',
        ques: 'How am I called?',
        answer: 'kitchen',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729864/English/objects/fmoupdliv94daydnhfrs.png',
      },
      {
        _id: 'prac-17',
        ques: 'How am I called?',
        answer: 'watch',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/ex179qdpamvdhnvkgptb.png',
      },
      {
        _id: 'prac-18',
        ques: 'How am I called?',
        answer: 'dining room',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/lwckmuox4qyb1ndvcogx.png',
      },
      {
        _id: 'prac-19',
        ques: 'How am I called?',
        answer: 'bedroom',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729853/English/objects/covo2jvjhrgefpytenb0.png',
      },
    ],
    [
      {
        _id: 'prac-20',
        ques: 'How am I called?',
        answer: 'living room',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729859/English/objects/ccqzxps9xyclaeejlurs.png',
      },
      {
        _id: 'prac-21',
        ques: 'How am I called?',
        answer: 'bathroom',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/zi3yw0nkll6tw0vgagmn.png',
      },
      {
        _id: 'prac-22',
        ques: 'How am I called?',
        answer: 'toilet',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/hzmmussobcl45npipmjf.png',
      },
      {
        _id: 'prac-23',
        ques: 'How am I called?',
        answer: 'garden',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729856/English/objects/mikktgbgpyehrsoihzdb.png',
      },
      {
        _id: 'prac-24',
        ques: 'How am I called?',
        answer: 'gas',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/i6oedykjtienesp2ithk.png',
      },
    ],
    [
      {
        _id: 'prac-25',
        ques: 'How am I called?',
        answer: 'computer',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/jqspxzezratlaqgx1d2q.png',
      },
      {
        _id: 'prac-26',
        ques: 'How am I called?',
        answer: 'lamp',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729860/English/objects/ldqnrcodpjscvm6xyemh.png',
      },
      {
        _id: 'prac-27',
        ques: 'How am I called?',
        answer: 'rug',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729863/English/objects/glzklv5n8pqobryjlptj.png',
      },
      {
        _id: 'prac-28',
        ques: 'How am I called?',
        answer: 'drink',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/dtpwvdzjgt4qw23khbpy.png',
      },
      {
        _id: 'prac-29',
        ques: 'How am I called?',
        answer: 'sleep',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729864/English/objects/auvbnbphbk7xihmnuxcj.png',
      },
    ],
    [
      {
        _id: 'prac-30',
        ques: 'How am I called?',
        answer: 'walk',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/n0indsur4inswu6lwmbx.png',
      },
      {
        _id: 'prac-31',
        ques: 'How am I called?',
        answer: 'cook',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729854/English/objects/j9vod3vwtqr7u9nuhnna.png',
      },
      {
        _id: 'prac-32',
        ques: 'How am I called?',
        answer: 'climb',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729853/English/objects/qtg0yzbfcj3fhgg8utiq.png',
      },
      {
        _id: 'prac-33',
        ques: 'How am I called?',
        answer: 'swim',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/jevcrpgjgwbrtoce85db.png',
      },
      {
        _id: 'prac-34',
        ques: 'How am I called?',
        answer: 'remember',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729862/English/objects/zwjxwlzgtfykwcuibjty.png',
      },
    ],
    [
      {
        _id: 'prac-35',
        ques: 'How am I called?',
        answer: 'fly',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729857/English/objects/rrljunrrdnpnjjzlrpjd.png',
      },
      {
        _id: 'prac-36',
        ques: 'How am I called?',
        answer: 'know',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729860/English/objects/t8pehve6c0zuqzsngugx.png',
      },
      {
        _id: 'prac-37',
        ques: 'How am I called?',
        answer: 'come in',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/igx3se02ffegziu9mwgx.png',
      },
      {
        _id: 'prac-38',
        ques: 'How am I called?',
        answer: 'work',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729868/English/objects/mo3ktw3tcwnfrttiozdr.png',
      },
      {
        _id: 'prac-39',
        ques: 'How am I called?',
        answer: 'build',
        img: tiger,
      },
    ],
    [
      {
        _id: 'prac-40',
        ques: 'How am I called?',
        answer: 'throw',
        img: tiger,
      },
      {
        _id: 'prac-41',
        ques: 'How am I called?',
        answer: 'cut',
        img: tiger,
      },
      {
        _id: 'prac-42',
        ques: 'How am I called?',
        answer: 'clean',
        img: tiger,
      },
      {
        _id: 'prac-43',
        ques: 'How am I called?',
        answer: 'feed',
        img: tiger,
      },
      {
        _id: 'prac-44',
        ques: 'How am I called?',
        answer: 'eat',
        img: tiger,
      },
    ],
    [
      {
        _id: 'prac-45',
        ques: 'How am I called?',
        answer: 'cucumber',
        img: tiger,
      },
      {
        _id: 'prac-46',
        ques: 'How am I called?',
        answer: 'egg',
        img: tiger,
      },
      {
        _id: 'prac-47',
        ques: 'How am I called?',
        answer: 'cookie',
        img: tiger,
      },
      {
        _id: 'prac-48',
        ques: 'How am I called?',
        answer: 'tea',
        img: tiger,
      },
      {
        _id: 'prac-49',
        ques: 'How am I called?',
        answer: 'pie',
        img: tiger,
      },
    ],
    [
      {
        _id: 'prac-50',
        ques: 'How am I called?',
        answer: 'hot dog',
        img: tiger,
      },
      {
        _id: 'prac-51',
        ques: 'How am I called?',
        answer: 'cereal',
        img: tiger,
      },
      {
        _id: 'prac-52',
        ques: 'How am I called?',
        answer: 'onion',
        img: tiger,
      },
      {
        _id: 'prac-53',
        ques: 'How am I called?',
        answer: 'coffee',
        img: tiger,
      },
      {
        _id: 'prac-54',
        ques: 'How am I called?',
        answer: 'plum',
        img: tiger,
      },
    ],
    [
      {
        _id: 'prac-55',
        ques: 'How am I called?',
        answer: 'candy',
        img: tiger,
      },
      {
        _id: 'prac-56',
        ques: 'How am I called?',
        answer: 'potato',
        img: tiger,
      },
      {
        _id: 'prac-57',
        ques: 'How am I called?',
        answer: 'peach',
        img: tiger,
      },
      {
        _id: 'prac-58',
        ques: 'How am I called?',
        answer: 'pepper',
        img: tiger,
      },
      {
        _id: 'prac-59',
        ques: 'How am I called?',
        answer: 'cheese',
        img: tiger,
      },
    ],
    [
      {
        _id: 'prac-60',
        ques: 'How am I called?',
        answer: 'tomato',
        img: tiger,
      },
      {
        _id: 'prac-61',
        ques: 'How am I called?',
        answer: 'apple',
        img: tiger,
      },
      {
        _id: 'prac-62',
        ques: 'How am I called?',
        answer: 'lettuce',
        img: tiger,
      },
      {
        _id: 'prac-63',
        ques: 'How am I called?',
        answer: 'bread',
        img: tiger,
      },
      {
        _id: 'prac-64',
        ques: 'How am I called?',
        answer: 'morning',
        img: tiger,
      },
    ],
    [
      {
        _id: 'prac-65',
        ques: 'How am I called?',
        answer: 'afternoon',
        img: tiger,
      },
      {
        _id: 'prac-66',
        ques: 'How am I called?',
        answer: 'evening',
        img: tiger,
      },
      {
        _id: 'prac-67',
        ques: 'How am I called?',
        answer: 'night',
        img: tiger,
      },
      {
        _id: 'prac-68',
        ques: 'How am I called?',
        answer: 'month',
        img: tiger,
      },
      {
        _id: 'prac-69',
        ques: 'How am I called?',
        answer: 'week',
        img: tiger,
      },
    ],
    [
      {
        _id: 'prac-70',
        ques: 'How am I called?',
        answer: 'year',
        img: tiger,
      },
      {
        _id: 'prac-71',
        ques: 'How am I called?',
        answer: 'summer',
        img: tiger,
      },
      {
        _id: 'prac-72',
        ques: 'How am I called?',
        answer: 'winter',
        img: tiger,
      },
      {
        _id: 'prac-73',
        ques: 'How am I called?',
        answer: 'winter',
        img: tiger,
      },
      {
        _id: 'prac-74',
        ques: 'How am I called?',
        answer: 'autumn',
        img: tiger,
      },
    ],
    [
      {
        _id: 'prac-75',
        ques: 'How am I called?',
        answer: 'spring',
        img: tiger,
      },
      {
        _id: 'prac-76',
        ques: 'How am I called?',
        answer: 'young',
        img: tiger,
      },
      {
        _id: 'prac-77',
        ques: 'How am I called?',
        answer: 'old',
        img: tiger,
      },
      {
        _id: 'prac-78',
        ques: 'How am I called?',
        answer: 'beautiful',
        img: tiger,
      },
      {
        _id: 'prac-79',
        ques: 'How am I called?',
        answer: 'ugly',
        img: tiger,
      },
    ],
    [
      {
        _id: 'prac-80',
        ques: 'How am I called?',
        answer: 'poor',
        img: tiger,
      },
      {
        _id: 'prac-81',
        ques: 'How am I called?',
        answer: 'rich',
        img: tiger,
      },
      {
        _id: 'prac-82',
        ques: 'How am I called?',
        answer: 'warm',
        img: tiger,
      },
      {
        _id: 'prac-83',
        ques: 'How am I called?',
        answer: 'cool',
        img: tiger,
      },
      {
        _id: 'prac-84',
        ques: 'How am I called?',
        answer: 'clean',
        img: tiger,
      },
    ],
    [
      {
        _id: 'prac-85',
        ques: 'How am I called?',
        answer: 'dirty',
        img: tiger,
      },
      {
        _id: 'prac-86',
        ques: 'How am I called?',
        answer: 'family',
        img: tiger,
      },
      {
        _id: 'prac-87',
        ques: 'How am I called?',
        answer: 'guard',
        img: tiger,
      },
      {
        _id: 'prac-88',
        ques: 'How am I called?',
        answer: 'children',
        img: tiger,
      },
      {
        _id: 'prac-89',
        ques: 'How am I called?',
        answer: 'king',
        img: tiger,
      },
    ],
    [
      {
        _id: 'prac-90',
        ques: 'How am I called?',
        answer: 'nurse',
        img: tiger,
      },
      {
        _id: 'prac-91',
        ques: 'How am I called?',
        answer: 'driver',
        img: tiger,
      },
      {
        _id: 'prac-92',
        ques: 'How am I called?',
        answer: 'doctor',
        img: tiger,
      },
      {
        _id: 'prac-93',
        ques: 'How am I called?',
        answer: 'waiter',
        img: tiger,
      },
    ],
  ],
  img: '',
};
