import animalsBg from '../assets/img/animals-bg.jpg';
import numbersBg from '../assets/img/numbers-bg.png';
import grammarBg from '../assets/img/grammar-bg.jpg';
import colorsBg from '../assets/img/colors-bg.png';
import countriesBg from '../assets/img/countries-bg.jpg';

const animals = {
  type: 'animals',
  img: animalsBg,
  tests: [
    [
      {
        _id: 'anml-0',
        ques: 'How am I called?',
        hint: 'd_g',
        answer: 'dog',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978284/English/animals/foz0mujfe9itqgq9uz3p.jpg',
      },
      {
        _id: 'anml-1',
        ques: 'How am I called?',
        hint: 't_g_r',
        answer: 'tiger',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978291/English/animals/yeeqfevhjtuomczfulsq.jpg',
      },
      {
        _id: 'anml-2',
        ques: 'How am I called?',
        hint: 'l__n',
        answer: 'lion',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978287/English/animals/iswdhcwkleqvkq2nh2ii.jpg',
      },
      {
        _id: 'anml-3',
        ques: 'How am I called?',
        hint: 'fi__',
        answer: 'fish',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978285/English/animals/yr9c3vb5bgdvmgddracp.jpg',
      },
      {
        _id: 'anml-4',
        ques: 'How am I called?',
        hint: 'c_t',
        answer: 'cat',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978293/English/animals/b9exxwly2lp0fnrkkkln.jpg',
      },
    ],
    [
      {
        _id: 'anml-5',
        ques: 'How am I called?',
        hint: '',
        answer: 'bird',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978299/English/animals/gkzuahfjuxoe90hrfwiq.png',
      },
      {
        _id: 'anml-6',
        ques: 'How am I called?',
        hint: '',
        answer: 'snake',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978381/English/animals/y7ummtbh7bau87ooimvq.jpg',
      },
      {
        _id: 'anml-7',
        ques: 'How am I called?',
        hint: '',
        answer: 'elephant',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978289/English/animals/waove4ssabqrbegmyy5x.jpg',
      },
      {
        _id: 'anml-8',
        ques: 'How am I called?',
        hint: '',
        answer: 'whale',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978292/English/animals/kvk6bcx0aylv6m8uyldm.jpg',
      },
      {
        _id: 'anml-9',
        ques: 'How am I called?',
        hint: '',
        answer: 'hamster',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978286/English/animals/ph34ykcpms9rvo5hfyfn.jpg',
      },
    ],
    [
      {
        _id: 'anml-10',
        ques: 'How am I called?',
        hint: '',
        answer: 'zebra',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978363/English/animals/vyt4ioaacclbmacfozmk.jpg',
      },
      {
        _id: 'anml-11',
        ques: 'How am I called?',
        hint: '',
        answer: 'bat',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978338/English/animals/ihcrbzkmliyaqota99xx.jpg',
      },
      {
        _id: 'anml-12',
        ques: 'How am I called?',
        hint: '',
        answer: 'bee',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978366/English/animals/rfsxbhfaakww41ztuoqa.jpg',
      },
      {
        _id: 'anml-13',
        ques: 'How am I called?',
        hint: '',
        answer: 'bear',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978365/English/animals/vpojlhflxvrgq20bmv38.jpg',
      },
      {
        _id: 'anml-14',
        ques: 'How am I called?',
        hint: '',
        answer: 'giraffe',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978371/English/animals/dtpskxdijzcre7l4p3ps.jpg',
      },
    ],
    [
      {
        _id: 'anml-15',
        ques: 'How am I called?',
        hint: '',
        answer: 'hippo',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978373/English/animals/bbsaktrgfcaizey89atq.png',
      },
      {
        _id: 'anml-16',
        ques: 'How am I called?',
        hint: '',
        answer: 'kangaroo',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978373/English/animals/jh697k4kz0g0kqicxbev.jpg',
      },
      {
        _id: 'anml-17',
        ques: 'How am I called?',
        hint: '',
        answer: 'monkey',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978374/English/animals/gqhw3otlkix8dav0tg9t.jpg',
      },
      {
        _id: 'anml-18',
        ques: 'How am I called?',
        hint: '',
        answer: 'mouse',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978376/English/animals/tsrp8a1gehbunipjvjfq.png',
      },
      {
        _id: 'anml-19',
        ques: 'How am I called?',
        hint: '',
        answer: 'owl',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978376/English/animals/lyisoj16hc9chiomtie4.jpg',
      },
    ],
    [
      {
        _id: 'anml-20',
        ques: 'How am I called?',
        hint: '',
        answer: 'parrot',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978377/English/animals/vqeqfcnkhdnzrlje6xts.jpg',
      },
      {
        _id: 'anml-21',
        ques: 'How am I called?',
        hint: '',
        answer: 'penguin',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978378/English/animals/qdykm2huaykgkhwuumpm.jpg',
      },
      {
        _id: 'anml-22',
        ques: 'How am I called?',
        hint: '',
        answer: 'spider',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978382/English/animals/pn0pebwemgcoqgd9rjzb.jpg',
      },
      {
        _id: 'anml-23',
        ques: 'How am I called?',
        hint: '',
        answer: 'squid',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978383/English/animals/lbmfmmephotbvchu9kph.jpg',
      },
      {
        _id: 'anml-24',
        ques: 'How am I called?',
        hint: '',
        answer: 'sloth',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978381/English/animals/lsof6f2fycoyqqr8nhdh.jpg',
      },
    ],
    [
      {
        _id: 'anml-25',
        ques: 'How am I called?',
        hint: '',
        answer: 'deer',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978369/English/animals/pyeh1ovzpzszt85uvodt.png',
      },
      {
        _id: 'anml-26',
        ques: 'How am I called?',
        hint: '',
        answer: 'cow',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978367/English/animals/hsub7eiuli977lpuerrt.jpg',
      },
      {
        _id: 'anml-27',
        ques: 'How am I called?',
        hint: '',
        answer: 'crab',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978370/English/animals/xfytnxa6yxwoz0b4whrv.png',
      },
      {
        _id: 'anml-28',
        ques: 'How am I called?',
        hint: '',
        answer: 'squirrel',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978364/English/animals/dnnypu4f1pevacomratw.jpg',
      },
      {
        _id: 'anml-29',
        ques: 'How am I called?',
        hint: '',
        answer: 'rhino',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978381/English/animals/slyakoj0mryko2swm9yj.png',
      },
    ],
    [
      {
        _id: 'anml-30',
        ques: 'How am I called?',
        hint: '',
        answer: 'ostrich',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978386/English/animals/hv6p2mfftarh6uxc2bj6.png',
      },
      {
        _id: 'anml-31',
        ques: 'How am I called?',
        hint: '',
        answer: 'wolf',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652979416/English/animals/trg7jycxrezyhdspx3le.jpg',
      },
      {
        _id: 'anml-32',
        ques: 'How am I called?',
        hint: '',
        answer: 'seal',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652979367/English/animals/klxb4x3arsxuznhkdhkh.jpg',
      },
      {
        _id: 'anml-33',
        ques: 'How am I called?',
        hint: '',
        answer: 'camel',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652979341/English/animals/odjap0wvgbob1sff6e64.jpg',
      },
      {
        _id: 'anml-34',
        ques: 'How am I called?',
        hint: '',
        answer: 'sheep',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652979303/English/animals/yft2rcpmm9qhlow3pni5.jpg',
      },
    ],
  ],
};
const colors = {
  type: 'colors',
  img: colorsBg,
  tests: [
    [
      {
        _id: 'color-0',
        ques: 'Name of the color?',
        hint: '',
        answer: 'red',
        color: '#FF4949',
      },
      {
        _id: 'color-1',
        ques: 'Name of the color?',
        hint: '',
        answer: 'blue',
        color: '#2155CD',
      },
      {
        _id: 'color-2',
        ques: 'Name of the color?',
        hint: '',
        answer: 'green',
        color: '#6BCB77',
      },
      {
        _id: 'color-3',
        ques: 'Name of the color?',
        hint: '',
        answer: 'white',
        color: '#FDF6EC',
      },
      {
        _id: 'color-4',
        ques: 'Name of the color?',
        hint: '',
        answer: 'yellow',
        color: '#F9D923',
      },
    ],
    [
      {
        _id: 'color-5',
        ques: 'Name of the color?',
        hint: '',
        answer: 'orange',
        color: '#F66B0E',
      },
      {
        _id: 'color-6',
        ques: 'Name of the color?',
        hint: '',
        answer: 'purple',
        color: '#8A39E1',
      },
      {
        _id: 'color-7',
        ques: 'Name of the color?',
        hint: '',
        answer: 'black',
        color: '#2C3333',
      },
      {
        _id: 'color-8',
        ques: 'Name of the color?',
        hint: '',
        answer: 'grey',
        color: '#D1D1D1',
      },
      {
        _id: 'color-9',
        ques: 'Name of the color?',
        hint: '',
        answer: 'pink',
        color: '#F806CC',
      },
    ],
    [
      {
        _id: 'color-10',
        ques: 'Name of the color?',
        hint: '',
        answer: 'brown',
        color: '#603601',
      },
      {
        _id: 'color-11',
        ques: 'Name of the color?',
        hint: '',
        answer: 'cyan',
        color: '#40DFEF',
      },
    ],
  ],
};
const countries = {
  type: 'countries',
  img: countriesBg,
  tests: [
    [
      {
        _id: 'coun-0',
        ques: 'Name of the country?',
        hint: '',
        answer: 'israel',
        img: 'https://flagcdn.com/il.svg',
      },
      {
        _id: 'coun-1',
        ques: 'Name of the country?',
        hint: '',
        answer: 'spain',
        img: 'https://flagcdn.com/es.svg',
      },
      {
        _id: 'coun-2',
        ques: 'Name of the country?',
        hint: '',
        answer: 'brazil',
        img: 'https://flagcdn.com/br.svg',
      },
      {
        _id: 'coun-3',
        ques: 'Name of the country?',
        hint: '',
        answer: 'egypt',
        img: 'https://flagcdn.com/eg.svg',
      },
      {
        _id: 'coun-4',
        ques: 'Name of the country?',
        hint: '',
        answer: 'france',
        img: 'https://flagcdn.com/fr.svg',
      },
    ],
    [
      {
        _id: 'coun-5',
        ques: 'Name of the country?',
        hint: '',
        answer: 'italy',
        img: 'https://flagcdn.com/it.svg',
      },
      {
        _id: 'coun-6',
        ques: 'Name of the country?',
        hint: '',
        answer: 'japan',
        img: 'https://flagcdn.com/jp.svg',
      },
      {
        _id: 'coun-7',
        ques: 'Name of the country?',
        hint: '',
        answer: 'mexico',
        img: 'https://flagcdn.com/mx.svg',
      },
      {
        _id: 'coun-8',
        ques: 'Name of the country?',
        hint: '',
        answer: 'poland',
        img: 'https://flagcdn.com/pl.svg',
      },
      {
        _id: 'coun-9',
        ques: 'Name of the country?',
        hint: '',
        answer: 'china',
        img: 'https://flagcdn.com/cn.svg',
      },
    ],
    [
      {
        _id: 'coun-10',
        ques: 'Name of the country?',
        hint: '',
        answer: 'colombia',
        img: 'https://flagcdn.com/co.svg',
      },
      {
        _id: 'coun-11',
        ques: 'Name of the country?',
        hint: '',
        answer: 'greece',
        img: 'https://flagcdn.com/gr.svg',
      },
      {
        _id: 'coun-12',
        ques: 'Name of the country?',
        hint: '',
        answer: 'morocco',
        img: 'https://flagcdn.com/ma.svg',
      },
      {
        _id: 'coun-13',
        ques: 'Name of the country?',
        hint: '',
        answer: 'norway',
        img: 'https://flagcdn.com/no.svg',
      },
      {
        _id: 'coun-14',
        ques: 'Name of the country?',
        hint: '',
        answer: 'united states of america',
        img: 'https://flagcdn.com/us.svg',
      },
    ],
  ],
};
const complete = {
  type: 'complete the sentence',
  background: 'linear-gradient(to top left, #e52a5a, #ff585f)',
  tests: [
    [
      {
        _id: 'comp-0',
        ques: 'Dan is _______ to the school',
        hint: '',
        answer: 'walking',
        color: '#FF4949',
      },
      {
        _id: 'comp-1',
        ques: 'Gali is ______ a banana',
        hint: '',
        answer: 'eating',
        color: '#2155CD',
      },
      {
        _id: 'comp-2',
        ques: 'The boy is __ the car',
        hint: '',
        answer: 'in',
        color: '#6BCB77',
      },
      {
        _id: 'comp-3',
        ques: 'The dog is _______',
        hint: '',
        answer: 'barking',
        color: '#FDF6EC',
      },
      {
        _id: 'comp-4',
        ques: 'Shay is _______',
        hint: '',
        answer: 'jumping',
        color: '#F9D923',
      },
    ],
    [
      {
        _id: 'comp-5',
        ques: 'Lior is drinking a glass of _____',
        hint: '',
        answer: 'water',
        color: '#F66B0E',
      },
      {
        _id: 'comp-6',
        ques: 'The children are ______ on the sofa',
        hint: '',
        answer: 'sitting',
        color: '#8A39E1',
      },
      {
        _id: 'comp-7',
        ques: 'Tom is at the ___ _______',
        hint: '',
        answer: 'bus station',
        color: '#2C3333',
      },
      {
        _id: 'comp-8',
        ques: 'Dan says "Look! that _____ looks like a rabbit"',
        hint: '',
        answer: 'cloud',
        color: '#D1D1D1',
      },
      {
        _id: 'comp-9',
        ques: 'The boy is wearing a ____ shirt',
        hint: '',
        answer: 'blue',
        color: '#F806CC',
      },
    ],
  ],
};

const practice = {
  type: 'practice',
  background: 'linear-gradient(to top left, #39b385, #9be15d)',
  tests: [
    [
      {
        _id: 'prac-0',
        ques: 'How am I called?',
        hint: '',
        answer: 'hospital',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/ptx8sl4hvx0yphw66agj.png',
      },
      {
        _id: 'prac-1',
        ques: 'How am I called?',
        hint: '',
        answer: 'museum',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729862/English/objects/k5buj4ujvc2iwn3badht.png',
      },
      {
        _id: 'prac-2',
        ques: 'How am I called?',
        hint: '',
        answer: 'theater',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/uyu0hbgv0snw1rj0iwx1.png',
      },
      {
        _id: 'prac-3',
        ques: 'How am I called?',
        hint: '',
        answer: 'market',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729861/English/objects/yhwvqt5o6d9mpbfxi05p.png',
      },
      {
        _id: 'prac-4',
        ques: 'How am I called?',
        hint: '',
        answer: 'town',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729870/English/objects/n7quumfggvdnrpl181wr.png',
      },
    ],
    [
      {
        _id: 'prac-5',
        ques: 'How am I called?',
        hint: '',
        answer: 'restaurant',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/tni0i9dtedcfhfiws2hf.png',
      },
      {
        _id: 'prac-6',
        ques: 'How am I called?',
        hint: '',
        answer: 'hotel',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/eli14fpvzjfsbmwktzeg.png',
      },
      {
        _id: 'prac-7',
        ques: 'How am I called?',
        hint: '',
        answer: 'fire station',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/vj2jwkycvnjqrq1w8pbq.png',
      },
      {
        _id: 'prac-8',
        ques: 'How am I called?',
        hint: '',
        answer: 'police station',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729864/English/objects/jhy4utmzpkoxggxjht5y.png',
      },
      {
        _id: 'prac-9',
        ques: 'How am I called?',
        hint: '',
        answer: 'bus station',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729853/English/objects/ow878bii5nlk0o5dbfqx.png',
      },
    ],
    [
      {
        _id: 'prac-10',
        ques: 'How am I called?',
        hint: '',
        answer: 'shop',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729862/English/objects/aboi1upztbfgfwtayatj.png',
      },
      {
        _id: 'prac-11',
        ques: 'How am I called?',
        hint: '',
        answer: 'home',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/jljaouxiutz47fqo0hj5.png',
      },
      {
        _id: 'prac-12',
        ques: 'How am I called?',
        hint: '',
        answer: 'electricity',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729859/English/objects/yed6zdoovyfwqdu8qzx4.png',
      },
      {
        _id: 'prac-13',
        ques: 'How am I called?',
        hint: '',
        answer: 'apartment',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729852/English/objects/rqnnhboylldz5q9wgadh.png',
      },
      {
        _id: 'prac-14',
        ques: 'How am I called?',
        hint: '',
        answer: 'sofa',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/z26qw25bl7oayvfczx1b.png',
      },
    ],
    [
      {
        _id: 'prac-15',
        ques: 'How am I called?',
        hint: '',
        answer: 'water',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/ybohpyljeqwrtnnj5bi4.png',
      },
      {
        _id: 'prac-16',
        ques: 'How am I called?',
        hint: '',
        answer: 'kitchen',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729864/English/objects/fmoupdliv94daydnhfrs.png',
      },
      {
        _id: 'prac-17',
        ques: 'How am I called?',
        hint: '',
        answer: 'watch',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/ex179qdpamvdhnvkgptb.png',
      },
      {
        _id: 'prac-18',
        ques: 'How am I called?',
        hint: '',
        answer: 'dining room',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/lwckmuox4qyb1ndvcogx.png',
      },
      {
        _id: 'prac-19',
        ques: 'How am I called?',
        hint: '',
        answer: 'bedroom',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729853/English/objects/covo2jvjhrgefpytenb0.png',
      },
    ],
    [
      {
        _id: 'prac-20',
        ques: 'How am I called?',
        hint: '',
        answer: 'living room',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729859/English/objects/ccqzxps9xyclaeejlurs.png',
      },
      {
        _id: 'prac-21',
        ques: 'How am I called?',
        hint: '',
        answer: 'bathroom',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/zi3yw0nkll6tw0vgagmn.png',
      },
      {
        _id: 'prac-22',
        ques: 'How am I called?',
        hint: '',
        answer: 'toilet',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/hzmmussobcl45npipmjf.png',
      },
      {
        _id: 'prac-23',
        ques: 'How am I called?',
        hint: '',
        answer: 'garden',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729856/English/objects/mikktgbgpyehrsoihzdb.png',
      },
      {
        _id: 'prac-24',
        ques: 'How am I called?',
        hint: '',
        answer: 'gas',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/i6oedykjtienesp2ithk.png',
      },
    ],
    [
      {
        _id: 'prac-25',
        ques: 'How am I called?',
        hint: '',
        answer: 'computer',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/jqspxzezratlaqgx1d2q.png',
      },
      {
        _id: 'prac-26',
        ques: 'How am I called?',
        hint: '',
        answer: 'lamp',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729860/English/objects/ldqnrcodpjscvm6xyemh.png',
      },
      {
        _id: 'prac-27',
        ques: 'How am I called?',
        hint: '',
        answer: 'rug',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729863/English/objects/glzklv5n8pqobryjlptj.png',
      },
      {
        _id: 'prac-28',
        ques: 'How am I called?',
        hint: '',
        answer: 'drink',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729858/English/objects/dtpwvdzjgt4qw23khbpy.png',
      },
      {
        _id: 'prac-29',
        ques: 'How am I called?',
        hint: '',
        answer: 'sleep',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729864/English/objects/auvbnbphbk7xihmnuxcj.png',
      },
    ],
    [
      {
        _id: 'prac-30',
        ques: 'How am I called?',
        hint: '',
        answer: 'walk',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729867/English/objects/n0indsur4inswu6lwmbx.png',
      },
      {
        _id: 'prac-31',
        ques: 'How am I called?',
        hint: '',
        answer: 'cook',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729854/English/objects/j9vod3vwtqr7u9nuhnna.png',
      },
      {
        _id: 'prac-32',
        ques: 'How am I called?',
        hint: '',
        answer: 'climb',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729853/English/objects/qtg0yzbfcj3fhgg8utiq.png',
      },
      {
        _id: 'prac-33',
        ques: 'How am I called?',
        hint: '',
        answer: 'swim',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729865/English/objects/jevcrpgjgwbrtoce85db.png',
      },
      {
        _id: 'prac-34',
        ques: 'How am I called?',
        hint: '',
        answer: 'remember',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729862/English/objects/zwjxwlzgtfykwcuibjty.png',
      },
    ],
    [
      {
        _id: 'prac-35',
        ques: 'How am I called?',
        hint: '',
        answer: 'fly',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729857/English/objects/rrljunrrdnpnjjzlrpjd.png',
      },
      {
        _id: 'prac-36',
        ques: 'How am I called?',
        hint: '',
        answer: 'know',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729860/English/objects/t8pehve6c0zuqzsngugx.png',
      },
      {
        _id: 'prac-37',
        ques: 'How am I called?',
        hint: '',
        answer: 'come in',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729855/English/objects/igx3se02ffegziu9mwgx.png',
      },
      {
        _id: 'prac-38',
        ques: 'How am I called?',
        hint: '',
        answer: 'work',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652729868/English/objects/mo3ktw3tcwnfrttiozdr.png',
      },
      {
        _id: 'prac-39',
        ques: 'How am I called?',
        hint: '',
        answer: 'build',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977499/English/objects/ulqrfrd5pakcllji0sfr.png',
      },
    ],
    [
      {
        _id: 'prac-40',
        ques: 'How am I called?',
        hint: '',
        answer: 'throw',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652978063/English/objects/cpoc2hk0sbpzpeih9bv5.png',
      },
      {
        _id: 'prac-41',
        ques: 'How am I called?',
        hint: '',
        answer: 'cut',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977415/English/objects/jr0i5za3lfwvmw8ila9i.png',
      },
      {
        _id: 'prac-42',
        ques: 'How am I called?',
        hint: '',
        answer: 'clean',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977415/English/objects/xy17w85hqjfpihxxpgg9.png',
      },
      {
        _id: 'prac-43',
        ques: 'How am I called?',
        hint: '',
        answer: 'feed',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977418/English/objects/wz65xzrla8yxejt4hyf4.png',
      },
      {
        _id: 'prac-44',
        ques: 'How am I called?',
        hint: '',
        answer: 'eat',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977418/English/objects/xcomx6xzbutzq7it8akg.png',
      },
    ],
    [
      {
        _id: 'prac-45',
        ques: 'How am I called?',
        hint: '',
        answer: 'cucumber',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977418/English/objects/eakxraffjx2xhjcaoevs.png',
      },
      {
        _id: 'prac-46',
        ques: 'How am I called?',
        hint: '',
        answer: 'egg',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977417/English/objects/wimvco1y7uturvtno4em.png',
      },
      {
        _id: 'prac-47',
        ques: 'How am I called?',
        hint: '',
        answer: 'cookie',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977418/English/objects/cmnjo8aljszrh8xr1wo5.png',
      },
      {
        _id: 'prac-48',
        ques: 'How am I called?',
        hint: '',
        answer: 'tea',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977419/English/objects/uv2pbq09wvdy85i3htbs.png',
      },
      {
        _id: 'prac-49',
        ques: 'How am I called?',
        hint: '',
        answer: 'pie',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977419/English/objects/gtg4tgqiknozfwjorewx.png',
      },
    ],
    [
      {
        _id: 'prac-50',
        ques: 'How am I called?',
        hint: '',
        answer: 'hot dog',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977431/English/objects/nmeek87ired1ickzq8vi.png',
      },
      {
        _id: 'prac-51',
        ques: 'How am I called?',
        hint: '',
        answer: 'cereal',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977422/English/objects/fxoli3hiem3cfxdr50ao.png',
      },
      {
        _id: 'prac-52',
        ques: 'How am I called?',
        hint: '',
        answer: 'onion',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977421/English/objects/bgaty195hkdr0fjevwom.png',
      },
      {
        _id: 'prac-53',
        ques: 'How am I called?',
        hint: '',
        answer: 'coffee',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977424/English/objects/rovesfjc07kt5wzt4xwh.png',
      },
      {
        _id: 'prac-54',
        ques: 'How am I called?',
        hint: '',
        answer: 'plum',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977421/English/objects/x5skqkvfbpnc0nbgsbmi.png',
      },
    ],
    [
      {
        _id: 'prac-55',
        ques: 'How am I called?',
        hint: '',
        answer: 'candy',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977423/English/objects/kbgi8cqwefp2g2ttsbrn.png',
      },
      {
        _id: 'prac-56',
        ques: 'How am I called?',
        hint: '',
        answer: 'potato',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977421/English/objects/weqsfc5wkxpx9c06qhie.png',
      },
      {
        _id: 'prac-57',
        ques: 'How am I called?',
        hint: '',
        answer: 'peach',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977424/English/objects/fe19i1yvz6rjvodzkaqs.png',
      },
      {
        _id: 'prac-58',
        ques: 'How am I called?',
        hint: '',
        answer: 'pepper',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977424/English/objects/fe7vyf7aypuj3ytu9wgv.png',
      },
      {
        _id: 'prac-59',
        ques: 'How am I called?',
        hint: '',
        answer: 'cheese',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977425/English/objects/dcwzg54lffa0ezcde24n.png',
      },
    ],
    [
      {
        _id: 'prac-60',
        ques: 'How am I called?',
        hint: '',
        answer: 'tomato',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977425/English/objects/qfkuby8ijw0ikj5nz030.png',
      },
      {
        _id: 'prac-61',
        ques: 'How am I called?',
        hint: '',
        answer: 'apple',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977425/English/objects/esd34kmhszuyp1eqxzui.png',
      },
      {
        _id: 'prac-62',
        ques: 'How am I called?',
        hint: '',
        answer: 'lettuce',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977430/English/objects/dnxn46jyfkh0obkre5ul.png',
      },
      {
        _id: 'prac-63',
        ques: 'How am I called?',
        hint: '',
        answer: 'bread',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977428/English/objects/dh8sbwan4xcucuj28oxq.png',
      },
      {
        _id: 'prac-64',
        ques: 'How am I called?',
        hint: '',
        answer: 'morning',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977428/English/objects/jqefjfeockmi4tyeyzr4.png',
      },
    ],
    [
      {
        _id: 'prac-65',
        ques: 'How am I called?',
        hint: '',
        answer: 'afternoon',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977429/English/objects/va8ea5ldqyhczspt9pw8.png',
      },
      {
        _id: 'prac-66',
        ques: 'How am I called?',
        hint: '',
        answer: 'evening',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977446/English/objects/exuld7wbgvdtjn5ywsot.png',
      },
      {
        _id: 'prac-67',
        ques: 'How am I called?',
        hint: '',
        answer: 'night',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977429/English/objects/zbzwl5uqpywix2lathyk.png',
      },
      {
        _id: 'prac-68',
        ques: 'How am I called?',
        hint: '',
        answer: 'month',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977430/English/objects/y7alod3dbma5jr3dxr0u.png',
      },
      {
        _id: 'prac-69',
        ques: 'How am I called?',
        hint: '',
        answer: 'week',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977430/English/objects/jexnnjnphum3sufvjlyp.webp',
      },
    ],
    [
      {
        _id: 'prac-70',
        ques: 'How am I called?',
        hint: '',
        answer: 'year',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977431/English/objects/f776wfqg9t527tpizrx9.png',
      },
      {
        _id: 'prac-71',
        ques: 'How am I called?',
        hint: '',
        answer: 'summer',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977434/English/objects/lw0dhmerceqvzfy6ymxy.png',
      },
      {
        _id: 'prac-72',
        ques: 'How am I called?',
        hint: '',
        answer: 'winter',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977432/English/objects/pf6o2uhl5kw5h4moicr0.png',
      },
      {
        _id: 'prac-73',
        ques: 'How am I called?',
        hint: '',
        answer: 'spring',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977439/English/objects/kblaeh5dtlz3fyatdczg.png',
      },
      {
        _id: 'prac-74',
        ques: 'How am I called?',
        hint: '',
        answer: 'autumn',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977434/English/objects/zjoezlxgudwq9sehrmoh.png',
      },
    ],
    [
      {
        _id: 'prac-75',
        ques: 'How am I called?',
        hint: '',
        answer: 'waiter',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977423/English/objects/kpztrfsjn3qum5iubn6w.png',
      },

      {
        _id: 'prac-76',
        ques: 'How am I called?',
        hint: '',
        answer: 'young',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977438/English/objects/da5bk3fkxejmfm6zdpq8.png',
      },
      {
        _id: 'prac-77',
        ques: 'How am I called?',
        hint: '',
        answer: 'old',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977446/English/objects/v9pe0mn7ivasilisq1xc.png',
      },
      {
        _id: 'prac-78',
        ques: 'How am I called?',
        hint: '',
        answer: 'beautiful',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977435/English/objects/sj0023fuzywjulj9zl8t.png',
      },
      {
        _id: 'prac-79',
        ques: 'How am I called?',
        hint: '',
        answer: 'ugly',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977437/English/objects/mwl4faeiqqhoyse5aswk.png',
      },
    ],
    [
      {
        _id: 'prac-80',
        ques: 'How am I called?',
        hint: '',
        answer: 'poor',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977437/English/objects/gfpfoj7bfxgeovqvinzv.png',
      },
      {
        _id: 'prac-81',
        ques: 'How am I called?',
        hint: '',
        answer: 'rich',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977439/English/objects/wfboqib7glmjthh6zenb.png',
      },
      {
        _id: 'prac-82',
        ques: 'How am I called?',
        hint: '',
        answer: 'warm',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977438/English/objects/twjwxryxk5vj6a8dwned.png',
      },
      {
        _id: 'prac-83',
        ques: 'How am I called?',
        hint: '',
        answer: 'cool',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977440/English/objects/b6irwzw9pr3benimmf4n.png',
      },
      {
        _id: 'prac-84',
        ques: 'How am I called?',
        hint: '',
        answer: 'clean',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977441/English/objects/rwe5f1q2vbhkviy3wtgr.png',
      },
    ],
    [
      {
        _id: 'prac-85',
        ques: 'How am I called?',
        hint: '',
        answer: 'dirty',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977444/English/objects/jf7nwz3pu7woyxkj4maj.png',
      },
      {
        _id: 'prac-86',
        ques: 'How am I called?',
        hint: '',
        answer: 'family',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977441/English/objects/cncgromkdlt1lrmvby5x.png',
      },
      {
        _id: 'prac-87',
        ques: 'How am I called?',
        hint: '',
        answer: 'guard',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977442/English/objects/gjofhmscnigkga5xza5f.png',
      },
      {
        _id: 'prac-88',
        ques: 'How am I called?',
        hint: '',
        answer: 'children',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977443/English/objects/g4xtt7tevie8eufmfgyk.png',
      },
      {
        _id: 'prac-89',
        ques: 'How am I called?',
        hint: '',
        answer: 'king',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977446/English/objects/yqp1uz53q2ooqpu6luy0.png',
      },
    ],
    [
      {
        _id: 'prac-90',
        ques: 'How am I called?',
        hint: '',
        answer: 'nurse',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977444/English/objects/dwu9671dkqz6yzhfufly.png',
      },
      {
        _id: 'prac-91',
        ques: 'How am I called?',
        hint: '',
        answer: 'driver',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977449/English/objects/xafeq6nc7eu38i6khnbo.png',
      },
      {
        _id: 'prac-92',
        ques: 'How am I called?',
        hint: '',
        answer: 'doctor',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652977416/English/objects/tvizbrjq9c1k7a9mk6fq.png',
      },
    ],
  ],
};
const numbers = {
  type: 'numbers',
  img: numbersBg,

  tests: [
    [
      {
        _id: 'nums-0',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'one',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/imzu3z5jkuejez1xddur.png',
      },
      {
        _id: 'nums-1',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'two',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/dfdwp5qxanii1lm0mkwd.png',
      },
      {
        _id: 'nums-2',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'three',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/ppsjjs6srfhibileuvcb.png',
      },
      {
        _id: 'nums-3',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'four',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/xoh4gbx3k2msue21jwht.png',
      },
      {
        _id: 'nums-4',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'five',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/jmxi0espyplpl90abo4h.png',
      },
    ],
    [
      {
        _id: 'nums-5',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'six',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/cpxqxxicrmz4sgfjh3zy.png',
      },
      {
        _id: 'nums-6',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'seven',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/zujac7d5vqn0comxfdgk.png',
      },
      {
        _id: 'nums-7',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'eight',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/l8qzwnkyroiac33jdmzp.png',
      },
      {
        _id: 'nums-8',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'nine',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/rccosygjuptc0i1bynpa.png',
      },
      {
        _id: 'nums-9',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'zero',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721282/English/numbers/tqjx8i0vucpzohvzkrin.png',
      },
    ],
    [
      {
        _id: 'nums-10',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'ten',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/rqsjxvtcsx1baxogqogu.png',
      },
      {
        _id: 'nums-11',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'eleven',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/ypxqdldkc0uofxyzdi9i.png',
      },
      {
        _id: 'nums-12',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'twelve',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721282/English/numbers/pmfi080ooslqbvvvwt1q.png',
      },
      {
        _id: 'nums-13',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'thirteen',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/vorjpwcg3x3hpyohs7d8.png',
      },
      {
        _id: 'nums-14',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'fourteen',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/vsxaaoc3is9ey4bwolks.png',
      },
    ],
    [
      {
        _id: 'nums-15',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'fifteen',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/jungjtihndn0eljgrbaz.png',
      },
      {
        _id: 'nums-16',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'sixteen',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/zibiic9hvizyvr7ddjf2.png',
      },
      {
        _id: 'nums-17',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'seventeen',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/mfaeudjpwdfmmjrzwvsp.png',
      },
      {
        _id: 'nums-18',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'eighteen',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/ns4avdolscqhuieghou6.png',
      },
      {
        _id: 'nums-19',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'nineteen',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/zn1dygpczuawkjoy6hdn.png',
      },
    ],
    [
      {
        _id: 'nums-20',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'twenty',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721282/English/numbers/e01oydpn6dbp4fltlnt5.png',
      },
      {
        _id: 'nums-21',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'thirty',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/psxf7vlzl20mlywabd1e.png',
      },
      {
        _id: 'nums-22',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'forty',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/zeeup3zvmdwxb80vjdhc.png',
      },
      {
        _id: 'nums-23',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'fifty',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/uoosk54w8srxz8ca2hup.png',
      },
      {
        _id: 'nums-24',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'sixty',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721281/English/numbers/mn2uozoz1pnb32yhrtlf.png',
      },
    ],
    [
      {
        _id: 'nums-25',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'seventy',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/pqo2ouqpivjxhcti57gx.png',
      },
      {
        _id: 'nums-26',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'eighty',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721278/English/numbers/nqwsebyvjsoiavk4zqyr.png',
      },
      {
        _id: 'nums-27',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'ninety',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721279/English/numbers/pjgder29xvef8ed5dhoi.png',
      },
      {
        _id: 'nums-28',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'one hundred',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/r42il9slxkhlw7nxevqp.png',
      },
      {
        _id: 'nums-29',
        ques: 'How do you say this number?',
        hint: '',
        answer: 'one thousand',
        img: 'https://res.cloudinary.com/dubjerksn/image/upload/v1652721280/English/numbers/stwvxh2mbrlsamivhjpf.png',
      },
    ],
  ],
};
const grammar = {
  type: 'grammar',
  img: grammarBg,
  tests: [
    [
      {
        _id: 'gram-0',
        ques: 'Eat in past simple',
        hint: '',
        answer: 'ate',
      },
      {
        _id: 'gram-1',
        ques: 'Sleep in past simple',
        hint: '',
        answer: 'slept',
      },
      {
        _id: 'gram-2',
        ques: 'Run in past simple',
        hint: '',
        answer: 'ran',
      },
      {
        _id: 'gram-3',
        ques: 'Throw in past simple',
        hint: '',
        answer: 'threw',
      },
      {
        _id: 'gram-4',
        ques: 'Send in past simple',
        hint: '',
        answer: 'sent',
      },
    ],
  ],
};

export const categories = [
  animals,
  colors,
  grammar,
  numbers,
  countries,
  practice,
  // complete,
];

// const classRoom = {
//   categories,
//   teacher: null,
//   students:[],
// }

export const checkIfDone = (user, test) => {
  let newUser = user?.completedTests
    ? user
    : { fullName: user.fullName, completedTests: [] };
  return test.every((t) => newUser.completedTests.includes(t._id));
};
